### PR TITLE
fix mcy to mcu

### PR DESCRIPTION
**Pull request by yw-fang**
Hi, Hung,

Thank you for your code. I didn't notice it until just now, it indeed has implemented some features I wanted to do before. Therefore, I could not help making some tests and reading some codes.

To some reasons, I found you used a module called mcy in some scripts like this:

```python
import mcu
mymcu = mcy.VASP()
mymcu.plot_band2D()
```

However, after I went through the code, I didn't find it defined. In addition, I tested the codes including 'mcy', they couldn't work. Considering what we really load in the script/codes is mcu, hence I changed mcy to mcu, and the scripts can run well now (for example: examples/Graphene_2D/mcu_run.py).

Therefore, I have changed all 'mcy' to 'mcu' except for two places in 

```
docs/build/html/_sources/plotting.rst.txt
```

and

```
docs/build/html/plotting.html
```

I will explain why I didn't revise these two files after you confirm my revisions.

### CODE REVIEW

**Comment by hungpham2017** [comment]
Thank you very much @yw-fang for your bug report. 
I didn't see your pull request until now. I need to set up a notification for my repos. Hope MCU is helopful for your work. Please let know if you need further assistance or any idea to develop the code.

**Comment by yw-fang** [comment]
Hi, @hungpham2017  thanks very much for your reply.
I will then create another pull request to explain why I didn't revise "docs/build/html/_sources/plotting.rst.txt" in the current pull request.

**Comment by hungpham2017** [comment]
Everything under docs/build/* are generated by Sphinx from the docs/source files. So no need to fix them. I am updating a few new functions in MCU together with their docs. hence, the docs page will be fixed in the next release of MCU (0.3). Thanks

**Comment by yw-fang** [comment]
@hungpham2017 

Oh, I didn't realize your quick reply until just now. I knew the build directory was created by the Sphinx, however, you can choose to only store them in our local computers. The reasons are listed in the new pull request. As you release the MCU 0.3, you can consider what I said in the new pull request.

**Pull request merged**
